# Generated by Django 5.2.9 on 2026-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Admin'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], max_length=20),
        ),
    ]
