# Generated by Django 5.2.9 on 2026-01-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='document_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='document_3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
